# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cc_ista <- function(D, lam, pMat, X0_, penalize_diag = 0L, BBstep = 1L, tol = 1e-5, maxit = 100L, info = 0L, trkeigs = 0L, DisS = 0L) {
    .Call('gconcordopt_cc_ista', PACKAGE = 'gconcordopt', D, lam, pMat, X0_, penalize_diag, BBstep, tol, maxit, info, trkeigs, DisS)
}

cc_fista <- function(D, lam, pMat, X0_, penalize_diag = 0L, steptype = 1L, tol = 1e-5, maxit = 100L, info = 0L, trkeigs = 0L, DisS = 0L) {
    .Call('gconcordopt_cc_fista', PACKAGE = 'gconcordopt', D, lam, pMat, X0_, penalize_diag, steptype, tol, maxit, info, trkeigs, DisS)
}

cc_elastic_ista <- function(D, lam, pMat, penalize_diag = 0L, BBstep = 1L, tol = 1e-5, maxit = 100L, info = 0L, trkeigs = 0L, DisS = 0L, en = 1.0) {
    .Call('gconcordopt_cc_elastic_ista', PACKAGE = 'gconcordopt', D, lam, pMat, penalize_diag, BBstep, tol, maxit, info, trkeigs, DisS, en)
}

